modLoader = "javafml"
loaderVersion = "*"
license = "All rights reserved"
issueTrackerURL = "https://github.com/an1by/SimpleWhitelist/issues"

[[mods]]
modId = "simplewhitelist"
version = "${mod_version}"
displayName = "SimpleWhitelist"
updateJSONURL = "https://modrinth.com/plugin/simplewhitelist/versions?l=forge"
displayURL = "https://modrinth.com/plugin/simplewhitelist"
logoFile = "icon.png"
authors = "An1by"
description = '''Simple whitelist system for your server'''

[[dependencies.simplewhitelist]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_dependency}"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplewhitelist]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"
